resume_from_checkpoint_path: '/mnt/NAS/patidarritesh/Pdf_2_LaTeX_v2_LONGFORMER/result/grounding_pdf_2_tex/20240521_004012/last.ckpt'
result_path: "result"
model_path: null
dataset_paths: ["/mnt/NAS/patidarritesh/Pdf_2_LaTeX_v2_LONGFORMER/pdf_2_tex/dataset/root/train.jsonl"]
tokenizer: "dataset/tokenizer.json"
exp_name: "grounding_pdf_2_tex"
train_batch_sizes: [1]
num_workers: 16
val_batch_sizes: [1]
val_batches: 1
input_size: [896,672]
max_length: 1024
max_position_embeddings: 1024
accumulate_grad_batches: 3
window_size: 7
patch_size: 4
embed_dim: 128
hidden_dimension: 1024
num_heads: [4, 8, 16, 32]
encoder_layer: [2, 2, 14, 2]
decoder_layer: 12
align_long_axis: False
num_nodes: 1
seed: 25
lr: 3e-6
min_lr: 7.5e-6
lr_step: 16
gamma: 0.9996
warmup_steps: 250
num_training_samples_per_epoch: 100000
max_epochs: 50
max_steps: -1
val_check_interval: null
check_val_every_n_epoch: 1
gradient_clip_val: 0.5
verbose: False
